spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bitespeeddb.mysql.database.azure.com:3306/Bitespeed
    username: sufiyan0211
    password: bite123Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080